# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomabi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='url',
            field=models.URLField(),
        ),
    ]
