# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomabi_app', '0002_auto_20170219_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('methodname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='manga',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomabi_app.Parser'),
        ),
    ]
