# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tomabi_app', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomabi_app.Chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomabi_app.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
