# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomabi_app', '0005_readingprogess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingProgess',
            new_name='ReadingProgress',
        ),
    ]
